/**
 * Tool Control API
 *
 * Tool 管控链路 API
 *
 * This file is auto generated by the code generation script.
 * Do not modify this file manually.
 * Use the `make codegen` command to regenerate.
 *
 * 当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
 * 使用 `make codegen` 命令重新生成。
 */

import * as $Devs from '@alicloud/devs20230714';
import * as $OpenApi from '@alicloud/openapi-client';
import * as $Util from '@alicloud/tea-util';

import { Config } from '../../utils/config';

// Handle ESM/CJS interop for Client class
const $DevsClient =
  // @ts-expect-error - ESM interop: default.default exists when imported as ESM namespace
  $Devs.default?.default ?? $Devs.default ?? $Devs;
import { ClientError, HTTPError, ServerError } from '../../utils/exception';
import { logger } from '../../utils/log';

/**
 * Tool Control API
 *
 * Tool 管控链路 API
 */
export class ToolControlAPI {
  private config?: Config;

  /**
   * Initialize API client
   * 初始化 API 客户端
   *
   * @param config - Global configuration object / 全局配置对象
   */
  constructor(config?: Config) {
    this.config = config;
  }

  /**
   * Get DevS client
   * 获取 DevS 客户端
   */
  protected getDevsClient(config?: Config): InstanceType<typeof $DevsClient> {
    const cfg = Config.withConfigs(this.config, config);

    // Use devs endpoint
    let endpoint = cfg.devsEndpoint;

    // Remove protocol prefix for SDK
    if (endpoint.startsWith('http://') || endpoint.startsWith('https://')) {
      endpoint = endpoint.split('://')[1];
    }

    const openApiConfig = new $OpenApi.Config({
      accessKeyId: cfg.accessKeyId,
      accessKeySecret: cfg.accessKeySecret,
      securityToken: cfg.securityToken || undefined,
      regionId: cfg.regionId,
      endpoint: endpoint,
      connectTimeout: cfg.timeout,
    });

    return new $DevsClient(openApiConfig);
  }

  /**
   * Get toolset
   * 获取工具
   *
   * @param name - Tool name / Tool 名称
   * @param headers - Request headers / 请求头
   * @param config - Configuration / 配置
   * @returns Toolset object / ToolSet 对象
   * @throws AgentRuntimeError - Throws on call failure / 调用失败时抛出
   * @throws ClientError - Client error / 客户端错误
   * @throws ServerError - Server error / 服务器错误
   */
  getToolset = async (params: {
    name: string;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$Devs.Toolset> => {
    const { name, headers, config } = params;

    try {
      const client = this.getDevsClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.getToolsetWithOptions(name, headers || {}, runtime);

      logger.debug(`API getToolset called, Request ID: ${response.body?.requestId}`);

      if (!response.body) {
        throw new Error('Empty response body');
      }

      return response.body;
    } catch (error) {
      if (error instanceof HTTPError) {
        throw error.toResourceError('ToolSet', name);
      }
      this.handleError(error, name);
    }
  };

  /**
   * List toolsets
   * 枚举 ToolSets
   *
   * @param input - List configuration / 枚举的配置
   * @param headers - Request headers / 请求头
   * @param config - Configuration / 配置
   * @returns ToolSet list / ToolSet 列表
   * @throws AgentRuntimeError - Throws on call failure / 调用失败时抛出
   * @throws ClientError - Client error / 客户端错误
   * @throws ServerError - Server error / 服务器错误
   */
  listToolsets = async (params: {
    input: $Devs.ListToolsetsRequest;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$Devs.ListToolsetsResponseBody> => {
    const { input, headers, config } = params;

    try {
      const client = this.getDevsClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listToolsetsWithOptions(input, headers || {}, runtime);

      logger.debug(`API listToolsets called, Request ID: ${response.body?.requestId}`);

      if (!response.body) {
        throw new Error('Empty response body');
      }

      return response.body;
    } catch (error) {
      this.handleError(error);
    }
  };

  /**
   * Create toolset
   * 创建工具集
   *
   * @param input - Toolset input / ToolSet 输入
   * @param headers - Request headers / 请求头
   * @param config - Configuration / 配置
   * @returns Toolset object / ToolSet 对象
   */
  createToolset = async (params: {
    input: $Devs.Toolset;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$Devs.Toolset> => {
    const { input, headers, config } = params;

    try {
      const client = this.getDevsClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.createToolsetWithOptions(
        new $Devs.CreateToolsetRequest({ body: input }),
        headers || {},
        runtime
      );

      logger.debug(`API createToolset called, Request ID: ${response.body?.requestId}`);

      if (!response.body) {
        throw new Error('Empty response body');
      }

      return response.body;
    } catch (error) {
      this.handleError(error, input?.name);
    }
  };

  /**
   * Update toolset
   * 更新工具集
   *
   * @param name - Toolset name / ToolSet 名称
   * @param input - Toolset input / ToolSet 输入
   * @param headers - Request headers / 请求头
   * @param config - Configuration / 配置
   * @returns Toolset object / ToolSet 对象
   */
  updateToolset = async (params: {
    name: string;
    input: $Devs.Toolset;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$Devs.Toolset> => {
    const { name, input, headers, config } = params;

    try {
      const client = this.getDevsClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.updateToolsetWithOptions(
        name,
        new $Devs.UpdateToolsetRequest({ body: input }),
        headers || {},
        runtime
      );

      logger.debug(`API updateToolset called, Request ID: ${response.body?.requestId}`);

      if (!response.body) {
        throw new Error('Empty response body');
      }

      return response.body;
    } catch (error) {
      this.handleError(error, name);
    }
  };

  /**
   * Delete toolset
   * 删除工具集
   *
   * @param name - Toolset name / ToolSet 名称
   * @param headers - Request headers / 请求头
   * @param config - Configuration / 配置
   * @returns Toolset object / ToolSet 对象
   */
  deleteToolset = async (params: {
    name: string;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$Devs.Toolset> => {
    const { name, headers, config } = params;

    try {
      const client = this.getDevsClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.deleteToolsetWithOptions(name, headers || {}, runtime);

      logger.debug(`API deleteToolset called, Request ID: ${response.body?.requestId}`);

      if (!response.body) {
        throw new Error('Empty response body');
      }

      return response.body;
    } catch (error) {
      this.handleError(error, name);
    }
  };

  /**
   * Handle API errors
   * 处理 API 错误
   */
  private handleError(error: unknown, _resourceName?: string): never {
    if (error && typeof error === 'object' && 'statusCode' in error) {
      const e = error as {
        statusCode: number;
        message: string;
        data?: { requestId?: string };
      };
      const statusCode = e.statusCode;
      const message = e.message || 'Unknown error';
      const requestId = e.data?.requestId;

      if (statusCode >= 400 && statusCode < 500) {
        throw new ClientError(statusCode, message, { requestId });
      } else if (statusCode >= 500) {
        throw new ServerError(statusCode, message, { requestId });
      }
    }
    throw error;
  }
}
