/**
 * This file is auto generated by the code generation script.
 * Do not modify this file manually.
 * Use the `bun run codegen` command to regenerate.
 *
 * 当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
 * 使用 `bun run codegen` 命令重新生成。
 */

// Source: model_control_api.yaml

import * as $AgentRun from "@alicloud/agentrun20250910";
import * as $Util from "@alicloud/tea-util";

import { Config } from "../../utils/config";
import { ControlAPI } from "../../utils/control-api";
import { ClientError, ServerError } from "../../utils/exception";
import { logger } from "../../utils/log";

/**
 * Model Control API
 */
export class ModelControlAPI extends ControlAPI {
  constructor(config?: Config) {
    super(config);
  }

  /**
   * Create model service
   *
   * @param params - Method parameters
   * @param params.input - Model service configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Created model service object
   */
  createModelService = async (params: { input: $AgentRun.CreateModelServiceInput; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelService> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.createModelServiceWithOptions(
        new $AgentRun.CreateModelServiceRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api createModelService, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelService;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Delete model service
   *
   * @param params - Method parameters
   * @param params.modelServiceName - Model service name
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Deleted model service object
   */
  deleteModelService = async (params: { modelServiceName: string; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelService> => {
    const { modelServiceName, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.deleteModelServiceWithOptions(
        modelServiceName,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api deleteModelService, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([modelServiceName])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelService;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Update model service
   *
   * @param params - Method parameters
   * @param params.modelServiceName - Model service name
   * @param params.input - Model service configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Updated model service object
   */
  updateModelService = async (params: { modelServiceName: string; input: $AgentRun.UpdateModelServiceInput; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelService> => {
    const { modelServiceName, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.updateModelServiceWithOptions(
        modelServiceName,
        new $AgentRun.UpdateModelServiceRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api updateModelService, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([modelServiceName, input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelService;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Get model service
   *
   * @param params - Method parameters
   * @param params.modelServiceName - Model service name
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Model service object
   */
  getModelService = async (params: { modelServiceName: string; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelService> => {
    const { modelServiceName, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.getModelServiceWithOptions(
        modelServiceName,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api getModelService, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([modelServiceName])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelService;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * List model services
   *
   * @param params - Method parameters
   * @param params.input - List options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns List of model service objects
   */
  listModelServices = async (params: { input: $AgentRun.ListModelServicesRequest; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ListModelServicesOutput> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listModelServicesWithOptions(
        input,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api listModelServices, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ListModelServicesOutput;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Create model proxy
   *
   * @param params - Method parameters
   * @param params.input - Model proxy configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Created model proxy object
   */
  createModelProxy = async (params: { input: $AgentRun.CreateModelProxyInput; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelProxy> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.createModelProxyWithOptions(
        new $AgentRun.CreateModelProxyRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api createModelProxy, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelProxy;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Delete model proxy
   *
   * @param params - Method parameters
   * @param params.modelProxyName - Model proxy name
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Deleted model proxy object
   */
  deleteModelProxy = async (params: { modelProxyName: string; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelProxy> => {
    const { modelProxyName, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.deleteModelProxyWithOptions(
        modelProxyName,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api deleteModelProxy, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([modelProxyName])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelProxy;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Update model proxy
   *
   * @param params - Method parameters
   * @param params.modelProxyName - Model proxy name
   * @param params.input - Model proxy configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Updated model proxy object
   */
  updateModelProxy = async (params: { modelProxyName: string; input: $AgentRun.UpdateModelProxyInput; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelProxy> => {
    const { modelProxyName, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.updateModelProxyWithOptions(
        modelProxyName,
        new $AgentRun.UpdateModelProxyRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api updateModelProxy, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([modelProxyName, input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelProxy;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Get model proxy
   *
   * @param params - Method parameters
   * @param params.modelProxyName - Model proxy name
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Model proxy object
   */
  getModelProxy = async (params: { modelProxyName: string; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ModelProxy> => {
    const { modelProxyName, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.getModelProxyWithOptions(
        modelProxyName,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api getModelProxy, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([modelProxyName])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ModelProxy;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * List model proxies
   *
   * @param params - Method parameters
   * @param params.input - List options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns List of model proxy objects
   */
  listModelProxies = async (params: { input: $AgentRun.ListModelProxiesRequest; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ListModelProxiesOutput> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listModelProxiesWithOptions(
        input,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api listModelProxies, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ListModelProxiesOutput;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

}
