/**
 * This file is auto generated by the code generation script.
 * Do not modify this file manually.
 * Use the `bun run codegen` command to regenerate.
 *
 * 当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
 * 使用 `bun run codegen` 命令重新生成。
 */

// Source: agent_runtime_control_api.yaml

import * as $AgentRun from '@alicloud/agentrun20250910';
import * as $Util from '@alicloud/tea-util';

import { Config } from '../../utils/config';
import { ControlAPI } from '../../utils/control-api';
import { ClientError, ServerError } from '../../utils/exception';
import { logger } from '../../utils/log';

/**
 * Agent Runtime Control API
 */
export class AgentRuntimeControlAPI extends ControlAPI {
  constructor(config?: Config) {
    super(config);
  }

  /**
   * Create Agent Runtime
   *
   * @param params - Method parameters
   * @param params.input - Agent Runtime configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Created Runtime object
   */
  createAgentRuntime = async (params: {
    input: $AgentRun.CreateAgentRuntimeInput;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntime> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.createAgentRuntimeWithOptions(
        new $AgentRun.CreateAgentRuntimeRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api createAgentRuntime, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntime;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Delete Agent Runtime
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Deleted Runtime object
   */
  deleteAgentRuntime = async (params: {
    agentId: string;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntime> => {
    const { agentId, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.deleteAgentRuntimeWithOptions(agentId, headers ?? {}, runtime);

      logger.debug(
        `request api deleteAgentRuntime, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntime;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Update Agent Runtime
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.input - Agent Runtime configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Updated Runtime object
   */
  updateAgentRuntime = async (params: {
    agentId: string;
    input: $AgentRun.UpdateAgentRuntimeInput;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntime> => {
    const { agentId, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.updateAgentRuntimeWithOptions(
        agentId,
        new $AgentRun.UpdateAgentRuntimeRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api updateAgentRuntime, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntime;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Get Agent Runtime
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.request - Get request options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Runtime object
   */
  getAgentRuntime = async (params: {
    agentId: string;
    request?: $AgentRun.GetAgentRuntimeRequest;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntime> => {
    const { agentId, request, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.getAgentRuntimeWithOptions(
        agentId,
        request ?? new $AgentRun.GetAgentRuntimeRequest({}),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api getAgentRuntime, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, request])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntime;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * List Agent Runtimes
   *
   * @param params - Method parameters
   * @param params.input - List options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns List of Runtime objects
   */
  listAgentRuntimes = async (params: {
    input: $AgentRun.ListAgentRuntimesRequest;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.ListAgentRuntimesOutput> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listAgentRuntimesWithOptions(input, headers ?? {}, runtime);

      logger.debug(
        `request api listAgentRuntimes, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.ListAgentRuntimesOutput;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Create Agent Runtime Endpoint
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.input - Endpoint configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Created Endpoint object
   */
  createAgentRuntimeEndpoint = async (params: {
    agentId: string;
    input: $AgentRun.CreateAgentRuntimeEndpointInput;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntimeEndpoint> => {
    const { agentId, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.createAgentRuntimeEndpointWithOptions(
        agentId,
        new $AgentRun.CreateAgentRuntimeEndpointRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api createAgentRuntimeEndpoint, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntimeEndpoint;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Delete Agent Runtime Endpoint
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.endpointId - Endpoint ID
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Deleted Endpoint object
   */
  deleteAgentRuntimeEndpoint = async (params: {
    agentId: string;
    endpointId: string;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntimeEndpoint> => {
    const { agentId, endpointId, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.deleteAgentRuntimeEndpointWithOptions(
        agentId,
        endpointId,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api deleteAgentRuntimeEndpoint, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, endpointId])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntimeEndpoint;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Update Agent Runtime Endpoint
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.endpointId - Endpoint ID
   * @param params.input - Endpoint configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Updated Endpoint object
   */
  updateAgentRuntimeEndpoint = async (params: {
    agentId: string;
    endpointId: string;
    input: $AgentRun.UpdateAgentRuntimeEndpointInput;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntimeEndpoint> => {
    const { agentId, endpointId, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.updateAgentRuntimeEndpointWithOptions(
        agentId,
        endpointId,
        new $AgentRun.UpdateAgentRuntimeEndpointRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api updateAgentRuntimeEndpoint, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, endpointId, input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntimeEndpoint;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Get Agent Runtime Endpoint
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.endpointId - Endpoint ID
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Endpoint object
   */
  getAgentRuntimeEndpoint = async (params: {
    agentId: string;
    endpointId: string;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.AgentRuntimeEndpoint> => {
    const { agentId, endpointId, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.getAgentRuntimeEndpointWithOptions(
        agentId,
        endpointId,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api getAgentRuntimeEndpoint, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, endpointId])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.AgentRuntimeEndpoint;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * List Agent Runtime Endpoints
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.input - List options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns List of Endpoint objects
   */
  listAgentRuntimeEndpoints = async (params: {
    agentId: string;
    input: $AgentRun.ListAgentRuntimeEndpointsRequest;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.ListAgentRuntimeEndpointsOutput> => {
    const { agentId, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listAgentRuntimeEndpointsWithOptions(
        agentId,
        input,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api listAgentRuntimeEndpoints, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.ListAgentRuntimeEndpointsOutput;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * List Agent Runtime Versions
   *
   * @param params - Method parameters
   * @param params.agentId - Agent Runtime ID
   * @param params.input - List options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns List of Version objects
   */
  listAgentRuntimeVersions = async (params: {
    agentId: string;
    input: $AgentRun.ListAgentRuntimeVersionsRequest;
    headers?: Record<string, string>;
    config?: Config;
  }): Promise<$AgentRun.ListAgentRuntimeVersionsOutput> => {
    const { agentId, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listAgentRuntimeVersionsWithOptions(
        agentId,
        input,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api listAgentRuntimeVersions, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([agentId, input])}\n  response: ${JSON.stringify(response.body?.data)}`
      );

      return response.body?.data as $AgentRun.ListAgentRuntimeVersionsOutput;
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'statusCode' in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || 'Unknown error';
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };
}
