/**
 * This file is auto generated by the code generation script.
 * Do not modify this file manually.
 * Use the `bun run codegen` command to regenerate.
 *
 * 当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
 * 使用 `bun run codegen` 命令重新生成。
 */

// Source: credential_control_api.yaml

import * as $AgentRun from "@alicloud/agentrun20250910";
import * as $Util from "@alicloud/tea-util";

import { Config } from "../../utils/config";
import { ControlAPI } from "../../utils/control-api";
import { ClientError, ServerError } from "../../utils/exception";
import { logger } from "../../utils/log";

/**
 * Credential Control API
 */
export class CredentialControlAPI extends ControlAPI {
  constructor(config?: Config) {
    super(config);
  }

  /**
   * Create credential
   *
   * @param params - Method parameters
   * @param params.input - Credential configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Created credential object
   */
  createCredential = async (params: { input: $AgentRun.CreateCredentialInput; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.Credential> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.createCredentialWithOptions(
        new $AgentRun.CreateCredentialRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api createCredential, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.Credential;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Delete credential
   *
   * @param params - Method parameters
   * @param params.credentialName - Credential name
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Deleted credential object
   */
  deleteCredential = async (params: { credentialName: string; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.Credential> => {
    const { credentialName, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.deleteCredentialWithOptions(
        credentialName,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api deleteCredential, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([credentialName])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.Credential;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Update credential
   *
   * @param params - Method parameters
   * @param params.credentialName - Credential name
   * @param params.input - Credential configuration
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Updated credential object
   */
  updateCredential = async (params: { credentialName: string; input: $AgentRun.UpdateCredentialInput; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.Credential> => {
    const { credentialName, input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.updateCredentialWithOptions(
        credentialName,
        new $AgentRun.UpdateCredentialRequest({ body: input }),
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api updateCredential, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([credentialName, input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.Credential;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * Get credential
   *
   * @param params - Method parameters
   * @param params.credentialName - Credential name
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns Credential object
   */
  getCredential = async (params: { credentialName: string; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.Credential> => {
    const { credentialName, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.getCredentialWithOptions(
        credentialName,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api getCredential, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([credentialName])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.Credential;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

  /**
   * List credentials
   *
   * @param params - Method parameters
   * @param params.input - List options
   * @param params.headers - Custom request headers
   * @param params.config - Optional config override
   * @returns List of credential objects
   */
  listCredentials = async (params: { input: $AgentRun.ListCredentialsRequest; headers?: Record<string, string>; config?: Config }): Promise<$AgentRun.ListCredentialsOutput> => {
    const { input, headers, config } = params;

    try {
      const client = this.getClient(config);
      const runtime = new $Util.RuntimeOptions({});

      const response = await client.listCredentialsWithOptions(
        input,
        headers ?? {},
        runtime
      );

      logger.debug(
        `request api listCredentials, request Request ID: ${response.body?.requestId}\n  request: ${JSON.stringify([input])}\n  response: ${JSON.stringify(response.body?.data)}`,
      );

      return response.body?.data as $AgentRun.ListCredentialsOutput;
    } catch (error: unknown) {
      if (error && typeof error === "object" && "statusCode" in error) {
        const e = error as { statusCode: number; message: string; data?: { requestId?: string } };
        const statusCode = e.statusCode;
        const message = e.message || "Unknown error";
        const requestId = e.data?.requestId;

        if (statusCode >= 400 && statusCode < 500) {
          throw new ClientError(statusCode, message, { requestId });
        } else if (statusCode >= 500) {
          throw new ServerError(statusCode, message, { requestId });
        }
      }
      throw error;
    }
  };

}
